<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/minfraud/http/src/HTTPBase.php',
    $vendorDir . '/minfraud/http/src/CreditCardFraudDetection.php',
    $vendorDir . '/minfraud/http/src/TelephoneVerification.php',
    $baseDir . '/gateway_common/WmfFramework.php',
);
