<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit496326f024bb73fb2c54d7fcabb5462e
{
    public static $files = array (
        '67153d798259e2422f77ee379077b565' => __DIR__ . '/..' . '/minfraud/http/src/HTTPBase.php',
        '038a1d49667b1c077e3f164315eba901' => __DIR__ . '/..' . '/minfraud/http/src/CreditCardFraudDetection.php',
        'bf34263f834e2781b79cae4d55a1d350' => __DIR__ . '/../..' . '/gateway_common/WmfFramework.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\Yaml\\' => 23,
        ),
        'P' => 
        array (
            'Predis\\' => 7,
            'PayWithAmazon\\' => 14,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'Predis\\' => 
        array (
            0 => __DIR__ . '/..' . '/predis/predis/src',
        ),
        'PayWithAmazon\\' => 
        array (
            0 => __DIR__ . '/..' . '/amzn/login-and-pay-with-amazon-sdk-php/PayWithAmazon',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 
            array (
                0 => __DIR__ . '/..' . '/psr/log',
            ),
            'PHPQueue' => 
            array (
                0 => __DIR__ . '/..' . '/coderkungfu/php-queue/src',
            ),
        ),
        'F' => 
        array (
            'FuseSource' => 
            array (
                0 => __DIR__ . '/..' . '/fusesource/stomp-php/src',
            ),
        ),
        'C' => 
        array (
            'Clio' => 
            array (
                0 => __DIR__ . '/..' . '/clio/clio/src',
            ),
        ),
    );

    public static $classMap = array (
        'AdyenAdapter' => __DIR__ . '/../..' . '/adyen_gateway/adyen.adapter.php',
        'AdyenGateway' => __DIR__ . '/../..' . '/adyen_gateway/adyen_gateway.body.php',
        'AdyenGatewayResult' => __DIR__ . '/../..' . '/adyen_gateway/adyen_resultswitcher.body.php',
        'AmazonAdapter' => __DIR__ . '/../..' . '/amazon_gateway/amazon.adapter.php',
        'AmazonBillingApi' => __DIR__ . '/../..' . '/amazon_gateway/amazon.api.php',
        'AmazonGateway' => __DIR__ . '/../..' . '/amazon_gateway/amazon_gateway.body.php',
        'AmountInCents' => __DIR__ . '/../..' . '/gateway_common/AmountInCents.php',
        'ArrayHelper' => __DIR__ . '/../..' . '/gateway_common/ArrayHelper.php',
        'CleanupRecurringLength' => __DIR__ . '/../..' . '/paypal_gateway/CleanupRecurringLength.php',
        'ClientSideValidationHelper' => __DIR__ . '/../..' . '/gateway_common/ClientSideValidationHelper.php',
        'ContributionTrackingPlusUnique' => __DIR__ . '/../..' . '/gateway_common/ContributionTrackingPlusUnique.php',
        'CurrencyRates' => __DIR__ . '/../..' . '/gateway_common/CurrencyRates.php',
        'CyclicalArray' => __DIR__ . '/../..' . '/globalcollect_gateway/CyclicalArray.php',
        'DataValidator' => __DIR__ . '/../..' . '/gateway_common/DataValidator.php',
        'DonationApi' => __DIR__ . '/../..' . '/gateway_common/donation.api.php',
        'DonationData' => __DIR__ . '/../..' . '/gateway_common/DonationData.php',
        'DonationLogProcessor' => __DIR__ . '/../..' . '/gateway_common/DonationLogProcessor.php',
        'DonationLoggerFactory' => __DIR__ . '/../..' . '/gateway_common/DonationLoggerFactory.php',
        'DonationProfiler' => __DIR__ . '/../..' . '/gateway_common/DonationProfiler.php',
        'DonationQueue' => __DIR__ . '/../..' . '/gateway_common/DonationQueue.php',
        'DonorEmail' => __DIR__ . '/../..' . '/gateway_common/DonorEmail.php',
        'DonorFullName' => __DIR__ . '/../..' . '/gateway_common/DonorFullName.php',
        'DonorLanguage' => __DIR__ . '/../..' . '/gateway_common/DonorLanguage.php',
        'EncodingMangler' => __DIR__ . '/../..' . '/gateway_common/EncodingMangler.php',
        'FallbackLogPrefixer' => __DIR__ . '/../..' . '/gateway_common/FallbackLogPrefixer.php',
        'FinalStatus' => __DIR__ . '/../..' . '/gateway_common/FinalStatus.php',
        'FiscalNumber' => __DIR__ . '/../..' . '/gateway_common/FiscalNumber.php',
        'GatewayAdapter' => __DIR__ . '/../..' . '/gateway_common/gateway.adapter.php',
        'GatewayPage' => __DIR__ . '/../..' . '/gateway_common/GatewayPage.php',
        'GatewayType' => __DIR__ . '/../..' . '/gateway_common/GatewayType.php',
        'GlobalCollectAdapter' => __DIR__ . '/../..' . '/globalcollect_gateway/globalcollect.adapter.php',
        'GlobalCollectGateway' => __DIR__ . '/../..' . '/globalcollect_gateway/globalcollect_gateway.body.php',
        'GlobalCollectGatewayResult' => __DIR__ . '/../..' . '/globalcollect_gateway/globalcollect_resultswitcher.body.php',
        'GlobalCollectGetDirectory' => __DIR__ . '/../..' . '/globalcollect_gateway/scripts/get_directory.php',
        'GlobalCollectOrphanAdapter' => __DIR__ . '/../..' . '/globalcollect_gateway/orphan.adapter.php',
        'GlobalCollectOrphanRectifier' => __DIR__ . '/../..' . '/globalcollect_gateway/GlobalCollectOrphanRectifier.php',
        'GlobalCollectRefundMaintenance' => __DIR__ . '/../..' . '/globalcollect_gateway/scripts/refund.php',
        'IngenicoFinancialNumber' => __DIR__ . '/../..' . '/globalcollect_gateway/IngenicoFinancialNumber.php',
        'IngenicoLanguage' => __DIR__ . '/../..' . '/globalcollect_gateway/IngenicoLanguage.php',
        'IngenicoMethodCodec' => __DIR__ . '/../..' . '/globalcollect_gateway/IngenicoMethodCodec.php',
        'IngenicoReturntoHelper' => __DIR__ . '/../..' . '/globalcollect_gateway/IngenicoReturntoHelper.php',
        'LCRun3' => __DIR__ . '/..' . '/zordius/lightncandy/src/lightncandy.php',
        'LightnCandy' => __DIR__ . '/..' . '/zordius/lightncandy/src/lightncandy.php',
        'LogPrefixProvider' => __DIR__ . '/../..' . '/gateway_common/gateway.adapter.php',
        'MessageUtils' => __DIR__ . '/../..' . '/gateway_common/MessageUtils.php',
        'NationalCurrencies' => __DIR__ . '/../..' . '/gateway_common/NationalCurrencies.php',
        'OrphanMaintenance' => __DIR__ . '/../..' . '/globalcollect_gateway/scripts/orphans.php',
        'PaymentMethod' => __DIR__ . '/../..' . '/gateway_common/PaymentMethod.php',
        'PaymentResult' => __DIR__ . '/../..' . '/gateway_common/PaymentResult.php',
        'PaymentTransactionResponse' => __DIR__ . '/../..' . '/gateway_common/PaymentTransactionResponse.php',
        'PaypalLegacyAdapter' => __DIR__ . '/../..' . '/paypal_gateway/legacy/paypal_legacy.adapter.php',
        'PaypalLegacyGateway' => __DIR__ . '/../..' . '/paypal_gateway/legacy/paypal_legacy_gateway.body.php',
        'PaypalLegacyLocale' => __DIR__ . '/../..' . '/paypal_gateway/legacy/PaypalLegacyLocale.php',
        'ResponseCodes' => __DIR__ . '/../..' . '/gateway_common/ResponseCodes.php',
        'ResponseProcessingException' => __DIR__ . '/../..' . '/gateway_common/ResponseProcessingException.php',
        'ResultPages' => __DIR__ . '/../..' . '/gateway_common/ResultPages.php',
        'StagingHelper' => __DIR__ . '/../..' . '/gateway_common/StagingHelper.php',
        'StreetAddress' => __DIR__ . '/../..' . '/gateway_common/StreetAddress.php',
        'UnstagingHelper' => __DIR__ . '/../..' . '/gateway_common/UnstagingHelper.php',
        'ValidationHelper' => __DIR__ . '/../..' . '/gateway_common/ValidationHelper.php',
        'WmfFrameworkLogHandler' => __DIR__ . '/../..' . '/gateway_common/WmfFrameworkLogHandler.php',
        'WmfFramework_Drupal' => __DIR__ . '/../..' . '/gateway_common/WmfFramework.drupal.php',
        'WmfFramework_Mediawiki' => __DIR__ . '/../..' . '/gateway_common/WmfFramework.mediawiki.php',
        'WorldpayAccountName' => __DIR__ . '/../..' . '/worldpay_gateway/WorldpayAccountName.php',
        'WorldpayAdapter' => __DIR__ . '/../..' . '/worldpay_gateway/worldpay.adapter.php',
        'WorldpayCurrency' => __DIR__ . '/../..' . '/worldpay_gateway/WorldpayCurrency.php',
        'WorldpayEmail' => __DIR__ . '/../..' . '/worldpay_gateway/WorldpayEmail.php',
        'WorldpayGateway' => __DIR__ . '/../..' . '/worldpay_gateway/worldpay_gateway.body.php',
        'WorldpayGatewayResult' => __DIR__ . '/../..' . '/worldpay_gateway/worldpay_resultswitcher.body.php',
        'WorldpayMethodCodec' => __DIR__ . '/../..' . '/worldpay_gateway/WorldpayMethodCodec.php',
        'WorldpayNarrativeStatement' => __DIR__ . '/../..' . '/worldpay_gateway/WorldpayNarrativeStatement.php',
        'WorldpayReturnto' => __DIR__ . '/../..' . '/worldpay_gateway/WorldpayReturnto.php',
        'WorldpayRoutingInfo' => __DIR__ . '/../..' . '/worldpay_gateway/WorldpayRoutingInfo.php',
        'WorldpayValidateApi' => __DIR__ . '/../..' . '/worldpay_gateway/worldpay.api.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit496326f024bb73fb2c54d7fcabb5462e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit496326f024bb73fb2c54d7fcabb5462e::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit496326f024bb73fb2c54d7fcabb5462e::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit496326f024bb73fb2c54d7fcabb5462e::$classMap;

        }, null, ClassLoader::class);
    }
}
